dubbo:
  application:
    name: service-consumer
  registry:
    address: 10.3.246.104  # zookeeper注册中心的地址
    port: 2181              # zookeeper注册中心的端口
    protocol: zookeeper
    subscribe: true
  protocol:
    name: dubbo
    host: 10.3.246.104
  consumer:
    timeout: 1000
    check: false  # 服务启动时检查被调用服务是否可用
    retries: 2    # 服务调用重试次数
    version: 1.0.0
  scan:
    base-packages: com.xavier.xos.api.service.XosService  # dubbo服务调用者所在的包